// Knockout JavaScript library v2.1.0
// (c) Steven Sanderson - http://knockoutjs.com/
// License: MIT (http://www.opensource.org/licenses/mit-license.php)

(function() {function i(v){throw v;}var m=!0,o=null,p=!1;function r(v){return function(){return v}};var u=window,w=document,da=navigator,E=window.jQuery,G=void 0;
function J(v){function ea(a,d,c,e,f){var g=[],a=b.k(function(){var a=d(c,f)||[];0<g.length&&(b.a.Pa(K(g),a),e&&e(c,a,f));g.splice(0,g.length);b.a.P(g,a)},o,{disposeWhenNodeIsRemoved:a,disposeWhen:function(){return 0==g.length||!b.a.X(g[0])}});return{N:g,k:a}}function K(a){for(;a.length&&!b.a.X(a[0]);)a.splice(0,1);if(1<a.length){for(var d=a[0],c=a[a.length-1],e=[d];d!==c;){d=d.nextSibling;if(!d)return;e.push(d)}Array.prototype.splice.apply(a,[0,a.length].concat(e))}return a}function P(a,b,c,e,f){var g=
Math.min,h=Math.max,j=[],k,l=a.length,n,s=b.length,q=s-l||1,F=l+s+1,x,z,Q;for(k=0;k<=l;k++){z=x;j.push(x=[]);Q=g(s,k+q);for(n=h(0,k-1);n<=Q;n++)x[n]=n?k?a[k-1]===b[n-1]?z[n-1]:g(z[n]||F,x[n-1]||F)+1:n+1:k+1}g=[];h=[];q=[];k=l;for(n=s;k||n;)s=j[k][n]-1,n&&s===j[k][n-1]?h.push(g[g.length]={status:c,value:b[--n],index:n}):k&&s===j[k-1][n]?q.push(g[g.length]={status:e,value:a[--k],index:k}):(g.push({status:"retained",value:b[--n]}),--k);if(h.length&&q.length)for(var a=10*l,B,b=c=0;(f||b<a)&&(B=h[c]);c++){for(e=
0;j=q[e];e++)if(B.value===j.value){B.moved=j.index;j.moved=B.index;q.splice(e,1);b=e=0;break}b+=e}return g.reverse()}function R(a,d,c,e,f){var f=f||{},g=a&&L(a),g=g&&g.ownerDocument,h=f.templateEngine||M;b.va.nb(c,h,g);c=h.renderTemplate(c,e,f,g);("number"!=typeof c.length||0<c.length&&"number"!=typeof c[0].nodeType)&&i(Error("Template engine must return an array of DOM nodes"));g=p;switch(d){case "replaceChildren":b.e.S(a,c);g=m;break;case "replaceNode":b.a.Pa(a,c);g=m;break;case "ignoreTargetNode":break;
default:i(Error("Unknown renderMode: "+d))}g&&(S(c,e),f.afterRender&&f.afterRender(c,e.$data));return c}function L(a){return a.nodeType?a:0<a.length?a[0]:o}function S(a,d){if(a.length){var c=a[0],e=a[a.length-1];T(c,e,function(a){b.za(d,a)});T(c,e,function(a){b.t.Ya(a,[d])})}}function T(a,d,c){for(var e,d=b.e.nextSibling(d);a&&(e=a)!==d;)a=b.e.nextSibling(e),(1===e.nodeType||8===e.nodeType)&&c(e)}function U(a,d,c){for(var a=b.g.Z(a),e=b.g.F,f=0;f<a.length;f++){var g=a[f].key;if(e.hasOwnProperty(g)){var h=
e[g];"function"===typeof h?(g=h(a[f].value))&&i(Error(g)):h||i(Error("This template engine does not support the '"+g+"' binding within its templates"))}}a="ko.__tr_ambtns(function(){return(function(){return{"+b.g.$(a)+"} })()})";return c.createJavaScriptEvaluatorBlock(a)+d}function V(a,d,c,e){function f(a){return function(){return j[a]}}function g(){return j}var h=0,j,k;b.k(function(){var l=c&&c instanceof b.A?c:new b.A(b.a.d(c)),n=l.$data;e&&b.Ua(a,l);if(j=("function"==typeof d?d():d)||b.K.instance.getBindings(a,
l)){if(0===h){h=1;for(var s in j){var q=b.c[s];q&&8===a.nodeType&&!b.e.z[s]&&i(Error("The binding '"+s+"' cannot be used with virtual elements"));if(q&&"function"==typeof q.init&&(q=(0,q.init)(a,f(s),g,n,l))&&q.controlsDescendantBindings)k!==G&&i(Error("Multiple bindings ("+k+" and "+s+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.")),k=s}h=2}if(2===h)for(s in j)(q=b.c[s])&&"function"==typeof q.update&&(0,q.update)(a,f(s),
g,n,l)}},o,{disposeWhenNodeIsRemoved:a});return{Gb:k===G}}function W(a,d,c){var e=m,f=1===d.nodeType;f&&b.e.Ka(d);if(f&&c||b.K.instance.nodeHasBindings(d))e=V(d,o,a,c).Gb;e&&X(a,d,!f)}function X(a,d,c){for(var e=b.e.firstChild(d);d=e;)e=b.e.nextSibling(d),W(a,d,c)}function Y(a,b){var c=Z(a,b);return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:o}function Z(a,b){for(var c=a,e=1,f=[];c=c.nextSibling;){if(H(c)&&(e--,0===e))return f;f.push(c);y(c)&&e++}b||i(Error("Cannot find closing comment tag to match: "+
a.nodeValue));return o}function H(a){return 8==a.nodeType&&(I?a.text:a.nodeValue).match(fa)}function y(a){return 8==a.nodeType&&(I?a.text:a.nodeValue).match(ga)}function N(a,b){for(var c=o;a!=c;)c=a,a=a.replace(ha,function(a,c){return b[c]});return a}function ia(){var a=[],d=[];this.save=function(c,e){var f=b.a.i(a,c);0<=f?d[f]=e:(a.push(c),d.push(e))};this.get=function(c){c=b.a.i(a,c);return 0<=c?d[c]:G}}function $(a,b,c){function e(e){var g=b(a[e]);switch(typeof g){case "boolean":case "number":case "string":case "function":f[e]=
g;break;case "object":case "undefined":var h=c.get(g);f[e]=h!==G?h:$(g,b,c)}}c=c||new ia;a=b(a);if(!("object"==typeof a&&a!==o&&a!==G&&!(a instanceof Date)))return a;var f=a instanceof Array?[]:{};c.save(a,f);var g=a;if(g instanceof Array){for(var h=0;h<g.length;h++)e(h);"function"==typeof g.toJSON&&e("toJSON")}else for(h in g)e(h);return f}function aa(a,d){if(a)if(8==a.nodeType){var c=b.t.La(a.nodeValue);c!=o&&d.push({kb:a,yb:c})}else if(1==a.nodeType)for(var c=0,e=a.childNodes,f=e.length;c<f;c++)aa(e[c],
d)}function ba(a,d,c){c&&d!==b.j.r(a)&&b.j.U(a,d);d!==b.j.r(a)&&b.a.xa(a,"change")}var b="undefined"!==typeof v?v:{};b.b=function(a,d){for(var c=a.split("."),e=b,f=0;f<c.length-1;f++)e=e[c[f]];e[c[c.length-1]]=d};b.s=function(a,b,c){a[b]=c};b.version="2.1.0";b.b("version",b.version);b.a=new function(){function a(a,d){if("input"!==b.a.u(a)||!a.type||"click"!=d.toLowerCase())return p;var c=a.type;return"checkbox"==c||"radio"==c}var d=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,c={},e={};c[/Firefox\/2/i.test(da.userAgent)?
"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];c.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");for(var f in c){var g=c[f];if(g.length)for(var h=0,j=g.length;h<j;h++)e[g[h]]=f}var k={propertychange:m},l,c=3;f=w.createElement("div");for(g=f.getElementsByTagName("i");f.innerHTML="<\!--[if gt IE "+ ++c+"]><i></i><![endif]--\>",g[0];);l=4<c?c:G;return{Fa:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],n:function(a,b){for(var d=
0,c=a.length;d<c;d++)b(a[d])},i:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var d=0,c=a.length;d<c;d++)if(a[d]===b)return d;return-1},bb:function(a,b,d){for(var c=0,e=a.length;c<e;c++)if(b.call(d,a[c]))return a[c];return o},ea:function(a,d){var c=b.a.i(a,d);0<=c&&a.splice(c,1)},Ba:function(a){for(var a=a||[],d=[],c=0,e=a.length;c<e;c++)0>b.a.i(d,a[c])&&d.push(a[c]);return d},W:function(a,b){for(var a=a||[],d=[],c=0,e=a.length;c<e;c++)d.push(b(a[c]));
return d},da:function(a,b){for(var a=a||[],d=[],c=0,e=a.length;c<e;c++)b(a[c])&&d.push(a[c]);return d},P:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var d=0,c=b.length;d<c;d++)a.push(b[d]);return a},extend:function(a,b){if(b)for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a},ia:function(a){for(;a.firstChild;)b.removeNode(a.firstChild)},Ab:function(a){for(var a=b.a.M(a),d=w.createElement("div"),c=0,e=a.length;c<e;c++)b.G(a[c]),d.appendChild(a[c]);return d},S:function(a,d){b.a.ia(a);
if(d)for(var c=0,e=d.length;c<e;c++)a.appendChild(d[c])},Pa:function(a,d){var c=a.nodeType?[a]:a;if(0<c.length){for(var e=c[0],f=e.parentNode,g=0,h=d.length;g<h;g++)f.insertBefore(d[g],e);g=0;for(h=c.length;g<h;g++)b.removeNode(c[g])}},Sa:function(a,b){7>l?a.setAttribute("selected",b):a.selected=b},D:function(a){return(a||"").replace(d,"")},Kb:function(a,d){for(var c=[],e=(a||"").split(d),f=0,g=e.length;f<g;f++){var h=b.a.D(e[f]);""!==h&&c.push(h)}return c},Hb:function(a,b){a=a||"";return b.length>
a.length?p:a.substring(0,b.length)===b},fb:function(a,b){for(var d="return ("+a+")",c=0;c<b;c++)d="with(sc["+c+"]) { "+d+" } ";return new Function("sc",d)},lb:function(a,b){if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a!=o;){if(a==b)return m;a=a.parentNode}return p},X:function(a){return b.a.lb(a,a.ownerDocument)},u:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},o:function(b,d,c){var e=l&&k[d];if(!e&&"undefined"!=typeof E){if(a(b,d))var f=c,c=function(a,
b){var d=this.checked;b&&(this.checked=b.gb!==m);f.call(this,a);this.checked=d};E(b).bind(d,c)}else!e&&"function"==typeof b.addEventListener?b.addEventListener(d,c,p):"undefined"!=typeof b.attachEvent?b.attachEvent("on"+d,function(a){c.call(b,a)}):i(Error("Browser doesn't support addEventListener or attachEvent"))},xa:function(b,d){(!b||!b.nodeType)&&i(Error("element must be a DOM node when calling triggerEvent"));if("undefined"!=typeof E){var c=[];a(b,d)&&c.push({gb:b.checked});E(b).trigger(d,c)}else"function"==
typeof w.createEvent?"function"==typeof b.dispatchEvent?(c=w.createEvent(e[d]||"HTMLEvents"),c.initEvent(d,m,m,u,0,0,0,0,0,p,p,p,p,0,b),b.dispatchEvent(c)):i(Error("The supplied element doesn't support dispatchEvent")):"undefined"!=typeof b.fireEvent?(a(b,d)&&(b.checked=b.checked!==m),b.fireEvent("on"+d)):i(Error("Browser doesn't support triggering events"))},d:function(a){return b.ma(a)?a():a},ba:function(a,d,c){if(d){var e=/[\w-]+/g,f=a.className.match(e)||[];b.a.n(d.match(e),function(a){var d=
b.a.i(f,a);0<=d?c||f.splice(d,1):c&&f.push(a)});a.className=f.join(" ")}},Ta:function(a,d){var c=b.a.d(d);if(c===o||c===G)c="";var e=b.e.firstChild(a);!e||3!=e.nodeType||b.e.nextSibling(e)?b.e.S(a,[w.createTextNode(c)]):e.data=c;b.a.ob(a)},Ra:function(a,b){a.name=b;if(7>=l)try{a.mergeAttributes(w.createElement("<input name='"+a.name+"'/>"),p)}catch(d){}},ob:function(a){9<=l&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},mb:function(a){if(9<=l){var b=a.style.width;a.style.width=
0;a.style.width=b}},Eb:function(a,d){for(var a=b.a.d(a),d=b.a.d(d),c=[],e=a;e<=d;e++)c.push(e);return c},M:function(a){for(var b=[],d=0,c=a.length;d<c;d++)b.push(a[d]);return b},Ib:6===l,Jb:7===l,Y:l,Ga:function(a,d){for(var c=b.a.M(a.getElementsByTagName("input")).concat(b.a.M(a.getElementsByTagName("textarea"))),e="string"==typeof d?function(a){return a.name===d}:function(a){return d.test(a.name)},f=[],g=c.length-1;0<=g;g--)e(c[g])&&f.push(c[g]);return f},Bb:function(a){return"string"==typeof a&&
(a=b.a.D(a))?u.JSON&&u.JSON.parse?u.JSON.parse(a):(new Function("return "+a))():o},ta:function(a,d,c){("undefined"==typeof JSON||"undefined"==typeof JSON.stringify)&&i(Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js"));return JSON.stringify(b.a.d(a),d,c)},Cb:function(a,d,c){var c=c||{},e=c.params||{},f=c.includeFields||this.Fa,g=a;if("object"==
typeof a&&"form"===b.a.u(a))for(var g=a.action,h=f.length-1;0<=h;h--)for(var j=b.a.Ga(a,f[h]),k=j.length-1;0<=k;k--)e[j[k].name]=j[k].value;var d=b.a.d(d),l=w.createElement("form");l.style.display="none";l.action=g;l.method="post";for(var C in d)a=w.createElement("input"),a.name=C,a.value=b.a.ta(b.a.d(d[C])),l.appendChild(a);for(C in e)a=w.createElement("input"),a.name=C,a.value=e[C],l.appendChild(a);w.body.appendChild(l);c.submitter?c.submitter(l):l.submit();setTimeout(function(){l.parentNode.removeChild(l)},
0)}}};b.b("utils",b.a);b.b("utils.arrayForEach",b.a.n);b.b("utils.arrayFirst",b.a.bb);b.b("utils.arrayFilter",b.a.da);b.b("utils.arrayGetDistinctValues",b.a.Ba);b.b("utils.arrayIndexOf",b.a.i);b.b("utils.arrayMap",b.a.W);b.b("utils.arrayPushAll",b.a.P);b.b("utils.arrayRemoveItem",b.a.ea);b.b("utils.extend",b.a.extend);b.b("utils.fieldsIncludedWithJsonPost",b.a.Fa);b.b("utils.getFormFields",b.a.Ga);b.b("utils.postJson",b.a.Cb);b.b("utils.parseJson",b.a.Bb);b.b("utils.registerEventHandler",b.a.o);b.b("utils.stringifyJson",
b.a.ta);b.b("utils.range",b.a.Eb);b.b("utils.toggleDomNodeCssClass",b.a.ba);b.b("utils.triggerEvent",b.a.xa);b.b("utils.unwrapObservable",b.a.d);Function.prototype.bind||(Function.prototype.bind=function(a){var b=this,c=Array.prototype.slice.call(arguments),a=c.shift();return function(){return b.apply(a,c.concat(Array.prototype.slice.call(arguments)))}});b.a.f=new function(){var a=0,d="__ko__"+(new Date).getTime(),c={};return{get:function(a,d){var c=b.a.f.getAll(a,p);return c===G?G:c[d]},set:function(a,
d,c){c===G&&b.a.f.getAll(a,p)===G||(b.a.f.getAll(a,m)[d]=c)},getAll:function(b,f){var g=b[d];if(!(g&&"null"!==g)){if(!f)return G;g=b[d]="ko"+a++;c[g]={}}return c[g]},clear:function(a){var b=a[d];b&&(delete c[b],a[d]=o)}}};b.b("utils.domData",b.a.f);b.b("utils.domData.clear",b.a.f.clear);b.a.H=new function(){function a(a,d){var e=b.a.f.get(a,c);e===G&&d&&(e=[],b.a.f.set(a,c,e));return e}function d(c){var e=a(c,p);if(e)for(var e=e.slice(0),j=0;j<e.length;j++)e[j](c);b.a.f.clear(c);"function"==typeof E&&
"function"==typeof E.cleanData&&E.cleanData([c]);if(f[c.nodeType])for(e=c.firstChild;c=e;)e=c.nextSibling,8===c.nodeType&&d(c)}var c="__ko_domNodeDisposal__"+(new Date).getTime(),e={1:m,8:m,9:m},f={1:m,9:m};return{ya:function(b,d){"function"!=typeof d&&i(Error("Callback must be a function"));a(b,m).push(d)},Oa:function(d,e){var f=a(d,p);f&&(b.a.ea(f,e),0==f.length&&b.a.f.set(d,c,G))},G:function(a){if(e[a.nodeType]&&(d(a),f[a.nodeType])){var c=[];b.a.P(c,a.getElementsByTagName("*"));for(var a=0,j=
c.length;a<j;a++)d(c[a])}},removeNode:function(a){b.G(a);a.parentNode&&a.parentNode.removeChild(a)}}};b.G=b.a.H.G;b.removeNode=b.a.H.removeNode;b.b("cleanNode",b.G);b.b("removeNode",b.removeNode);b.b("utils.domNodeDisposal",b.a.H);b.b("utils.domNodeDisposal.addDisposeCallback",b.a.H.ya);b.b("utils.domNodeDisposal.removeDisposeCallback",b.a.H.Oa);b.a.qa=function(a){var d;if("undefined"!=typeof E){if((d=E.clean([a]))&&d[0]){for(a=d[0];a.parentNode&&11!==a.parentNode.nodeType;)a=a.parentNode;a.parentNode&&
a.parentNode.removeChild(a)}}else{var c=b.a.D(a).toLowerCase();d=w.createElement("div");c=c.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!c.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!c.indexOf("<td")||!c.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];a="ignored<div>"+c[1]+a+c[2]+"</div>";for("function"==typeof u.innerShiv?d.appendChild(u.innerShiv(a)):d.innerHTML=a;c[0]--;)d=d.lastChild;d=b.a.M(d.lastChild.childNodes)}return d};b.a.aa=function(a,
d){b.a.ia(a);d=b.a.d(d);if(d!==o&&d!==G)if("string"!=typeof d&&(d=d.toString()),"undefined"!=typeof E)E(a).html(d);else for(var c=b.a.qa(d),e=0;e<c.length;e++)a.appendChild(c[e])};b.b("utils.parseHtmlFragment",b.a.qa);b.b("utils.setHtml",b.a.aa);var O={};b.t={oa:function(a){"function"!=typeof a&&i(Error("You can only pass a function to ko.memoization.memoize()"));var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);O[b]=a;return"<\!--[ko_memo:"+
b+"]--\>"},Xa:function(a,b){var c=O[a];c===G&&i(Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized."));try{return c.apply(o,b||[]),m}finally{delete O[a]}},Ya:function(a,d){var c=[];aa(a,c);for(var e=0,f=c.length;e<f;e++){var g=c[e].kb,h=[g];d&&b.a.P(h,d);b.t.Xa(c[e].yb,h);g.nodeValue="";g.parentNode&&g.parentNode.removeChild(g)}},La:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:o}};b.b("memoization",b.t);b.b("memoization.memoize",b.t.oa);b.b("memoization.unmemoize",
b.t.Xa);b.b("memoization.parseMemoText",b.t.La);b.b("memoization.unmemoizeDomNodeAndDescendants",b.t.Ya);b.Ea={throttle:function(a,d){a.throttleEvaluation=d;var c=o;return b.k({read:a,write:function(b){clearTimeout(c);c=setTimeout(function(){a(b)},d)}})},notify:function(a,d){a.equalityComparer="always"==d?r(p):b.m.fn.equalityComparer;return a}};b.b("extenders",b.Ea);b.Va=function(a,d,c){this.target=a;this.fa=d;this.jb=c;b.s(this,"dispose",this.B)};b.Va.prototype.B=function(){this.vb=m;this.jb()};
b.T=function(){this.w={};b.a.extend(this,b.T.fn);b.s(this,"subscribe",this.ua);b.s(this,"extend",this.extend);b.s(this,"getSubscriptionsCount",this.qb)};b.T.fn={ua:function(a,d,c){var c=c||"change",a=d?a.bind(d):a,e=new b.Va(this,a,function(){b.a.ea(this.w[c],e)}.bind(this));this.w[c]||(this.w[c]=[]);this.w[c].push(e);return e},notifySubscribers:function(a,d){d=d||"change";this.w[d]&&b.Q.sb(function(){b.a.n(this.w[d].slice(0),function(b){b&&b.vb!==m&&b.fa(a)})},this)},qb:function(){var a=0,b;for(b in this.w)this.w.hasOwnProperty(b)&&
(a+=this.w[b].length);return a},extend:function(a){var d=this;if(a)for(var c in a){var e=b.Ea[c];"function"==typeof e&&(d=e(d,a[c]))}return d}};b.Ia=function(a){return"function"==typeof a.ua&&"function"==typeof a.notifySubscribers};b.b("subscribable",b.T);b.b("isSubscribable",b.Ia);var A=[];b.Q={cb:function(a){A.push({fa:a,Da:[]})},end:function(){A.pop()},Na:function(a){b.Ia(a)||i(Error("Only subscribable things can act as dependencies"));if(0<A.length){var d=A[A.length-1];d&&!(0<=b.a.i(d.Da,a))&&
(d.Da.push(a),d.fa(a))}},sb:function(a,b){try{A.push(o),a.call(b)}finally{A.pop()}}};var ja={undefined:m,"boolean":m,number:m,string:m};b.m=function(a){function d(){if(0<arguments.length){if(!d.equalityComparer||!d.equalityComparer(c,arguments[0]))d.J(),c=arguments[0],d.I();return this}b.Q.Na(d);return c}var c=a;b.T.call(d);d.C=function(){return c};d.I=function(){d.notifySubscribers(c)};d.J=function(){d.notifySubscribers(c,"beforeChange")};b.a.extend(d,b.m.fn);b.s(d,"peek",d.C);b.s(d,"valueHasMutated",
d.I);b.s(d,"valueWillMutate",d.J);return d};b.m.fn={equalityComparer:function(a,b){return a===o||typeof a in ja?a===b:p}};var D=b.m.Db="__ko_proto__";b.m.fn[D]=b.m;b.ka=function(a,d){return a===o||a===G||a[D]===G?p:a[D]===d?m:b.ka(a[D],d)};b.ma=function(a){return b.ka(a,b.m)};b.Ja=function(a){return"function"==typeof a&&a[D]===b.m||"function"==typeof a&&a[D]===b.k&&a.rb?m:p};b.b("observable",b.m);b.b("isObservable",b.ma);b.b("isWriteableObservable",b.Ja);b.R=function(a){0==arguments.length&&(a=[]);
a!==o&&(a!==G&&!("length"in a))&&i(Error("The argument passed when initializing an observable array must be an array, or null, or undefined."));var d=b.m(a);b.a.extend(d,b.R.fn);return d};b.R.fn={remove:function(a){for(var b=this.C(),c=[],e="function"==typeof a?a:function(b){return b===a},f=0;f<b.length;f++){var g=b[f];e(g)&&(0===c.length&&this.J(),c.push(g),b.splice(f,1),f--)}c.length&&this.I();return c},removeAll:function(a){if(a===G){var d=this.C(),c=d.slice(0);this.J();d.splice(0,d.length);this.I();
return c}return!a?[]:this.remove(function(d){return 0<=b.a.i(a,d)})},destroy:function(a){var b=this.C(),c="function"==typeof a?a:function(b){return b===a};this.J();for(var e=b.length-1;0<=e;e--)c(b[e])&&(b[e]._destroy=m);this.I()},destroyAll:function(a){return a===G?this.destroy(r(m)):!a?[]:this.destroy(function(d){return 0<=b.a.i(a,d)})},indexOf:function(a){var d=this();return b.a.i(d,a)},replace:function(a,b){var c=this.indexOf(a);0<=c&&(this.J(),this.C()[c]=b,this.I())}};b.a.n("pop push reverse shift sort splice unshift".split(" "),
function(a){b.R.fn[a]=function(){var b=this.C();this.J();b=b[a].apply(b,arguments);this.I();return b}});b.a.n(["slice"],function(a){b.R.fn[a]=function(){var b=this();return b[a].apply(b,arguments)}});b.b("observableArray",b.R);b.k=function(a,d,c){function e(){b.a.n(q,function(a){a.B()});q=[]}function f(){var a=h.throttleEvaluation;a&&0<=a?(clearTimeout(B),B=setTimeout(g,a)):g()}function g(){if(!l)if(k&&z())F();else{l=m;try{var a=b.a.W(q,function(a){return a.target});b.Q.cb(function(d){var c;0<=(c=
b.a.i(a,d))?a[c]=G:q.push(d.ua(f))});for(var c=n.call(d),e=a.length-1;0<=e;e--)a[e]&&q.splice(e,1)[0].B();k=m;h.notifySubscribers(j,"beforeChange");j=c}finally{b.Q.end()}h.notifySubscribers(j);l=p}}function h(){if(0<arguments.length)return"function"===typeof s?s.apply(d,arguments):i(Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.")),this;k||g();b.Q.Na(h);return j}var j,k=p,l=p,n=a;n&&"object"==typeof n?
(c=n,n=c.read):(c=c||{},n||(n=c.read));"function"!=typeof n&&i(Error("Pass a function that returns the value of the ko.computed"));var s=c.write;d||(d=c.owner);var q=[],F=e,x="object"==typeof c.disposeWhenNodeIsRemoved?c.disposeWhenNodeIsRemoved:o,z=c.disposeWhen||r(p);if(x){F=function(){b.a.H.Oa(x,arguments.callee);e()};b.a.H.ya(x,F);var v=z,z=function(){return!b.a.X(x)||v()}}var B=o;h.C=function(){k||g();return j};h.pb=function(){return q.length};h.rb="function"===typeof c.write;h.B=function(){F()};
b.T.call(h);b.a.extend(h,b.k.fn);c.deferEvaluation!==m&&g();b.s(h,"peek",h.C);b.s(h,"dispose",h.B);b.s(h,"getDependenciesCount",h.pb);return h};b.ub=function(a){return b.ka(a,b.k)};v=b.m.Db;b.k[v]=b.m;b.k.fn={};b.k.fn[v]=b.k;b.b("dependentObservable",b.k);b.b("computed",b.k);b.b("isComputed",b.ub);b.Wa=function(a){0==arguments.length&&i(Error("When calling ko.toJS, pass the object you want to convert."));return $(a,function(a){for(var c=0;b.ma(a)&&10>c;c++)a=a();return a})};b.toJSON=function(a,d,
c){a=b.Wa(a);return b.a.ta(a,d,c)};b.b("toJS",b.Wa);b.b("toJSON",b.toJSON);b.j={r:function(a){switch(b.a.u(a)){case "option":return a.__ko__hasDomDataOptionValue__===m?b.a.f.get(a,b.c.options.pa):7>=b.a.Y?a.getAttributeNode("value").specified?a.value:a.text:a.value;case "select":return 0<=a.selectedIndex?b.j.r(a.options[a.selectedIndex]):G;default:return a.value}},U:function(a,d){switch(b.a.u(a)){case "option":switch(typeof d){case "string":b.a.f.set(a,b.c.options.pa,G);"__ko__hasDomDataOptionValue__"in
a&&delete a.__ko__hasDomDataOptionValue__;a.value=d;break;default:b.a.f.set(a,b.c.options.pa,d),a.__ko__hasDomDataOptionValue__=m,a.value="number"===typeof d?d:""}break;case "select":for(var c=a.options.length-1;0<=c;c--)if(b.j.r(a.options[c])==d){a.selectedIndex=c;break}break;default:if(d===o||d===G)d="";a.value=d}}};b.b("selectExtensions",b.j);b.b("selectExtensions.readValue",b.j.r);b.b("selectExtensions.writeValue",b.j.U);var ha=/\@ko_token_(\d+)\@/g,ka=["true","false"],la=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i;
b.g={F:[],Z:function(a){var d=b.a.D(a);if(3>d.length)return[];"{"===d.charAt(0)&&(d=d.substring(1,d.length-1));for(var a=[],c=o,e,f=0;f<d.length;f++){var g=d.charAt(f);if(c===o)switch(g){case '"':case "'":case "/":c=f,e=g}else if(g==e&&"\\"!==d.charAt(f-1)){g=d.substring(c,f+1);a.push(g);var h="@ko_token_"+(a.length-1)+"@",d=d.substring(0,c)+h+d.substring(f+1),f=f-(g.length-h.length),c=o}}e=c=o;for(var j=0,k=o,f=0;f<d.length;f++){g=d.charAt(f);if(c===o)switch(g){case "{":c=f;k=g;e="}";break;case "(":c=
f;k=g;e=")";break;case "[":c=f,k=g,e="]"}g===k?j++:g===e&&(j--,0===j&&(g=d.substring(c,f+1),a.push(g),h="@ko_token_"+(a.length-1)+"@",d=d.substring(0,c)+h+d.substring(f+1),f-=g.length-h.length,c=o))}e=[];d=d.split(",");c=0;for(f=d.length;c<f;c++)j=d[c],k=j.indexOf(":"),0<k&&k<j.length-1?(g=j.substring(k+1),e.push({key:N(j.substring(0,k),a),value:N(g,a)})):e.push({unknown:N(j,a)});return e},$:function(a){for(var d="string"===typeof a?b.g.Z(a):a,c=[],a=[],e,f=0;e=d[f];f++)if(0<c.length&&c.push(","),
e.key){var g;a:{g=e.key;var h=b.a.D(g);switch(h.length&&h.charAt(0)){case "'":case '"':break a;default:g="'"+h+"'"}}e=e.value;c.push(g);c.push(":");c.push(e);e=b.a.D(e);0<=b.a.i(ka,b.a.D(e).toLowerCase())?e=p:(h=e.match(la),e=h===o?p:h[1]?"Object("+h[1]+")"+h[2]:e);e&&(0<a.length&&a.push(", "),a.push(g+" : function(__ko_value) { "+e+" = __ko_value; }"))}else e.unknown&&c.push(e.unknown);d=c.join("");0<a.length&&(d=d+", '_ko_property_writers' : { "+a.join("")+" } ");return d},xb:function(a,d){for(var c=
0;c<a.length;c++)if(b.a.D(a[c].key)==d)return m;return p},ca:function(a,d,c,e,f){if(!a||!b.Ja(a)){if((a=d()._ko_property_writers)&&a[c])a[c](e)}else(!f||a()!==e)&&a(e)}};b.b("expressionRewriting",b.g);b.b("expressionRewriting.bindingRewriteValidators",b.g.F);b.b("expressionRewriting.parseObjectLiteral",b.g.Z);b.b("expressionRewriting.preProcessBindings",b.g.$);b.b("jsonExpressionRewriting",b.g);b.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",b.g.$);var I="<\!--test--\>"===w.createComment("test").text,
ga=I?/^<\!--\s*ko(?:\s+(.+\s*\:[\s\S]*))?\s*--\>$/:/^\s*ko(?:\s+(.+\s*\:[\s\S]*))?\s*$/,fa=I?/^<\!--\s*\/ko\s*--\>$/:/^\s*\/ko\s*$/,ma={ul:m,ol:m};b.e={z:{},childNodes:function(a){return y(a)?Z(a):a.childNodes},ja:function(a){if(y(a))for(var a=b.e.childNodes(a),d=0,c=a.length;d<c;d++)b.removeNode(a[d]);else b.a.ia(a)},S:function(a,d){if(y(a)){b.e.ja(a);for(var c=a.nextSibling,e=0,f=d.length;e<f;e++)c.parentNode.insertBefore(d[e],c)}else b.a.S(a,d)},Ma:function(a,b){y(a)?a.parentNode.insertBefore(b,
a.nextSibling):a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},Ha:function(a,d,c){c?y(a)?a.parentNode.insertBefore(d,c.nextSibling):c.nextSibling?a.insertBefore(d,c.nextSibling):a.appendChild(d):b.e.Ma(a,d)},firstChild:function(a){return!y(a)?a.firstChild:!a.nextSibling||H(a.nextSibling)?o:a.nextSibling},nextSibling:function(a){y(a)&&(a=Y(a));return a.nextSibling&&H(a.nextSibling)?o:a.nextSibling},Za:function(a){return(a=y(a))?a[1]:o},Ka:function(a){if(ma[b.a.u(a)]){var d=a.firstChild;
if(d){do if(1===d.nodeType){var c;c=d.firstChild;var e=o;if(c){do if(e)e.push(c);else if(y(c)){var f=Y(c,m);f?c=f:e=[c]}else H(c)&&(e=[c]);while(c=c.nextSibling)}if(c=e){e=d.nextSibling;for(f=0;f<c.length;f++)e?a.insertBefore(c[f],e):a.appendChild(c[f])}}while(d=d.nextSibling)}}}};b.b("virtualElements",b.e);b.b("virtualElements.allowedBindings",b.e.z);b.b("virtualElements.emptyNode",b.e.ja);b.b("virtualElements.insertAfter",b.e.Ha);b.b("virtualElements.prepend",b.e.Ma);b.b("virtualElements.setDomNodeChildren",
b.e.S);b.K=function(){this.eb={}};b.a.extend(b.K.prototype,{nodeHasBindings:function(a){switch(a.nodeType){case 1:return a.getAttribute("data-bind")!=o;case 8:return b.e.Za(a)!=o;default:return p}},getBindings:function(a,b){var c=this.getBindingsString(a,b);return c?this.parseBindingsString(c,b):o},getBindingsString:function(a){switch(a.nodeType){case 1:return a.getAttribute("data-bind");case 8:return b.e.Za(a);default:return o}},parseBindingsString:function(a,d){try{var c=d.$data,c="object"==typeof c&&
c!=o?[c,d]:[d],e=c.length,f=this.eb,g=e+"_"+a,h;if(!(h=f[g])){var j=" { "+b.g.$(a)+" } ";h=f[g]=b.a.fb(j,e)}return h(c)}catch(k){i(Error("Unable to parse bindings.\nMessage: "+k+";\nBindings value: "+a))}}});b.K.instance=new b.K;b.b("bindingProvider",b.K);b.c={};b.A=function(a,d,c){d?(b.a.extend(this,d),this.$parentContext=d,this.$parent=d.$data,this.$parents=(d.$parents||[]).slice(0),this.$parents.unshift(this.$parent)):(this.$parents=[],this.$root=a,this.ko=b);this.$data=a;c&&(this[c]=a)};b.A.prototype.createChildContext=
function(a,d){return new b.A(a,this,d)};b.A.prototype.extend=function(a){var d=b.a.extend(new b.A,this);return b.a.extend(d,a)};b.Ua=function(a,d){if(2==arguments.length)b.a.f.set(a,"__ko_bindingContext__",d);else return b.a.f.get(a,"__ko_bindingContext__")};b.Aa=function(a,d,c){1===a.nodeType&&b.e.Ka(a);return V(a,d,c,m)};b.$a=function(a,b){(1===b.nodeType||8===b.nodeType)&&X(a,b,m)};b.za=function(a,b){b&&(1!==b.nodeType&&8!==b.nodeType)&&i(Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node"));
b=b||u.document.body;W(a,b,m)};b.ha=function(a){switch(a.nodeType){case 1:case 8:var d=b.Ua(a);if(d)return d;if(a.parentNode)return b.ha(a.parentNode)}return G};b.ib=function(a){return(a=b.ha(a))?a.$data:G};b.b("bindingHandlers",b.c);b.b("applyBindings",b.za);b.b("applyBindingsToDescendants",b.$a);b.b("applyBindingsToNode",b.Aa);b.b("contextFor",b.ha);b.b("dataFor",b.ib);b.a.n(["click"],function(a){b.c[a]={init:function(d,c,e,f){return b.c.event.init.call(this,d,function(){var b={};b[a]=c();return b},
e,f)}}});b.c.event={init:function(a,d,c,e){var f=d()||{},g;for(g in f)(function(){var f=g;"string"==typeof f&&b.a.o(a,f,function(a){var g,l=d()[f];if(l){var n=c();try{var s=b.a.M(arguments);s.unshift(e);g=l.apply(e,s)}finally{g!==m&&(a.preventDefault?a.preventDefault():a.returnValue=p)}n[f+"Bubble"]===p&&(a.cancelBubble=m,a.stopPropagation&&a.stopPropagation())}})})()}};b.c.submit={init:function(a,d,c,e){"function"!=typeof d()&&i(Error("The value for a submit binding must be a function"));b.a.o(a,
"submit",function(b){var c,h=d();try{c=h.call(e,a)}finally{c!==m&&(b.preventDefault?b.preventDefault():b.returnValue=p)}})}};b.c.visible={update:function(a,d){var c=b.a.d(d()),e="none"!=a.style.display;c&&!e?a.style.display="":!c&&e&&(a.style.display="none")}};b.c.enable={update:function(a,d){var c=b.a.d(d());c&&a.disabled?a.removeAttribute("disabled"):!c&&!a.disabled&&(a.disabled=m)}};b.c.disable={update:function(a,d){b.c.enable.update(a,function(){return!b.a.d(d())})}};b.c.value={init:function(a,
d,c){function e(){var e=d(),f=b.j.r(a);b.g.ca(e,c,"value",f,m)}var f=["change"],g=c().valueUpdate;g&&("string"==typeof g&&(g=[g]),b.a.P(f,g),f=b.a.Ba(f));if(b.a.Y&&("input"==a.tagName.toLowerCase()&&"text"==a.type&&"off"!=a.autocomplete&&(!a.form||"off"!=a.form.autocomplete))&&-1==b.a.i(f,"propertychange")){var h=p;b.a.o(a,"propertychange",function(){h=m});b.a.o(a,"blur",function(){if(h){h=p;e()}})}b.a.n(f,function(d){var c=e;if(b.a.Hb(d,"after")){c=function(){setTimeout(e,0)};d=d.substring(5)}b.a.o(a,
d,c)})},update:function(a,d){var c="select"===b.a.u(a),e=b.a.d(d()),f=b.j.r(a),g=e!=f;0===e&&(0!==f&&"0"!==f)&&(g=m);g&&(f=function(){b.j.U(a,e)},f(),c&&setTimeout(f,0));c&&0<a.length&&ba(a,e,p)}};b.c.options={update:function(a,d,c){"select"!==b.a.u(a)&&i(Error("options binding applies only to SELECT elements"));for(var e=0==a.length,f=b.a.W(b.a.da(a.childNodes,function(a){return a.tagName&&"option"===b.a.u(a)&&a.selected}),function(a){return b.j.r(a)||a.innerText||a.textContent}),g=a.scrollTop,h=
b.a.d(d());0<a.length;)b.G(a.options[0]),a.remove(0);if(h){var c=c(),j=c.optionsIncludeDestroyed;"number"!=typeof h.length&&(h=[h]);if(c.optionsCaption){var k=w.createElement("option");b.a.aa(k,c.optionsCaption);b.j.U(k,G);a.appendChild(k)}for(var d=0,l=h.length;d<l;d++){var n=h[d];if(!n||!n._destroy||j){var k=w.createElement("option"),s=function(a,b,d){var c=typeof b;return"function"==c?b(a):"string"==c?a[b]:d},q=s(n,c.optionsValue,n);b.j.U(k,b.a.d(q));n=s(n,c.optionsText,q);b.a.Ta(k,n);a.appendChild(k)}}h=
a.getElementsByTagName("option");d=j=0;for(l=h.length;d<l;d++)0<=b.a.i(f,b.j.r(h[d]))&&(b.a.Sa(h[d],m),j++);a.scrollTop=g;e&&"value"in c&&ba(a,b.a.d(c.value),m);b.a.mb(a)}}};b.c.options.pa="__ko.optionValueDomData__";b.c.selectedOptions={init:function(a,d,c){b.a.o(a,"change",function(){var e=d(),f=[];b.a.n(a.getElementsByTagName("option"),function(a){a.selected&&f.push(b.j.r(a))});b.g.ca(e,c,"value",f)})},update:function(a,d){"select"!=b.a.u(a)&&i(Error("values binding applies only to SELECT elements"));
var c=b.a.d(d());c&&"number"==typeof c.length&&b.a.n(a.getElementsByTagName("option"),function(a){var d=0<=b.a.i(c,b.j.r(a));b.a.Sa(a,d)})}};b.c.text={update:function(a,d){b.a.Ta(a,d())}};b.e.z.text=m;b.c.html={init:function(){return{controlsDescendantBindings:m}},update:function(a,d){b.a.aa(a,d())}};b.c.css={update:function(a,d){var c=b.a.d(d());if("object"==typeof c)for(var e in c){var f=b.a.d(c[e]);b.a.ba(a,e,f)}else c=String(c||""),b.a.ba(a,a.__ko__cssValue,p),a.__ko__cssValue=c,b.a.ba(a,c,m)}};
b.c.style={update:function(a,d){var c=b.a.d(d()||{}),e;for(e in c)if("string"==typeof e){var f=b.a.d(c[e]);a.style[e]=f||""}}};b.c.uniqueName={init:function(a,d){if(d()){var c="ko_unique_"+ ++b.c.uniqueName.hb;b.a.Ra(a,c)}}};b.c.uniqueName.hb=0;b.c.checked={init:function(a,d,c){b.a.o(a,"click",function(){var e;if("checkbox"==a.type)e=a.checked;else if("radio"==a.type&&a.checked)e=a.value;else return;var f=d();"checkbox"==a.type&&b.a.d(f)instanceof Array?(e=b.a.i(b.a.d(f),a.value),a.checked&&0>e?f.push(a.value):
!a.checked&&0<=e&&f.splice(e,1)):b.g.ca(f,c,"checked",e,m)});"radio"==a.type&&!a.name&&b.c.uniqueName.init(a,r(m))},update:function(a,d){var c=b.a.d(d());"checkbox"==a.type?a.checked=c instanceof Array?0<=b.a.i(c,a.value):c:"radio"==a.type&&(a.checked=a.value==c)}};var ca={"class":"className","for":"htmlFor"};b.c.attr={update:function(a,d){var c=b.a.d(d())||{},e;for(e in c)if("string"==typeof e){var f=b.a.d(c[e]),g=f===p||f===o||f===G;g&&a.removeAttribute(e);8>=b.a.Y&&e in ca?(e=ca[e],g?a.removeAttribute(e):
a[e]=f):g||a.setAttribute(e,f.toString());"name"===e&&b.a.Ra(a,g?"":f.toString())}}};b.c.hasfocus={init:function(a,d,c){function e(e){a.__ko_hasfocusUpdating=m;var f=a.ownerDocument;"activeElement"in f&&(e=f.activeElement===a);f=d();b.g.ca(f,c,"hasfocus",e,m);a.__ko_hasfocusUpdating=p}var f=e.bind(o,m),g=e.bind(o,p);b.a.o(a,"focus",f);b.a.o(a,"focusin",f);b.a.o(a,"blur",g);b.a.o(a,"focusout",g)},update:function(a,d){if(!a.__ko_hasfocusUpdating){var c=b.a.d(d());c?a.focus():a.blur();b.a.xa(a,c?"focusin":
"focusout")}}};b.c["with"]={p:function(a){return function(){var d=a();return{"if":d,data:d,templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c["with"].p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c["with"].p(d),c,e,f)}};b.g.F["with"]=p;b.e.z["with"]=m;b.c["if"]={p:function(a){return function(){return{"if":a(),templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c["if"].p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c["if"].p(d),
c,e,f)}};b.g.F["if"]=p;b.e.z["if"]=m;b.c.ifnot={p:function(a){return function(){return{ifnot:a(),templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c.ifnot.p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c.ifnot.p(d),c,e,f)}};b.g.F.ifnot=p;b.e.z.ifnot=m;b.c.foreach={p:function(a){return function(){var d=b.a.d(a());return!d||"number"==typeof d.length?{foreach:d,templateEngine:b.q.L}:{foreach:d.data,as:d.as,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,
beforeRemove:d.beforeRemove,afterRender:d.afterRender,templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c.foreach.p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c.foreach.p(d),c,e,f)}};b.g.F.foreach=p;b.e.z.foreach=m;b.v=function(){};b.v.prototype.renderTemplateSource=function(){i(Error("Override renderTemplateSource"))};b.v.prototype.createJavaScriptEvaluatorBlock=function(){i(Error("Override createJavaScriptEvaluatorBlock"))};b.v.prototype.makeTemplateSource=
function(a,d){if("string"==typeof a){var d=d||w,c=d.getElementById(a);c||i(Error("Cannot find template with ID "+a));return new b.l.h(c)}if(1==a.nodeType||8==a.nodeType)return new b.l.O(a);i(Error("Unknown template type: "+a))};b.v.prototype.renderTemplate=function(a,b,c,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,b,c)};b.v.prototype.isTemplateRewritten=function(a,b){return this.allowTemplateRewriting===p?m:this.makeTemplateSource(a,b).data("isRewritten")};b.v.prototype.rewriteTemplate=
function(a,b,c){a=this.makeTemplateSource(a,c);b=b(a.text());a.text(b);a.data("isRewritten",m)};b.b("templateEngine",b.v);var na=/(<[a-z]+\d*(\s+(?!data-bind=)[a-z0-9\-]+(=(\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind=(["'])([\s\S]*?)\5/gi,oa=/<\!--\s*ko\b\s*([\s\S]*?)\s*--\>/g;b.va={nb:function(a,d,c){d.isTemplateRewritten(a,c)||d.rewriteTemplate(a,function(a){return b.va.zb(a,d)},c)},zb:function(a,b){return a.replace(na,function(a,e,f,g,h,j,k){return U(k,e,b)}).replace(oa,function(a,e){return U(e,"<\!-- ko --\>",
b)})},ab:function(a){return b.t.oa(function(d,c){d.nextSibling&&b.Aa(d.nextSibling,a,c)})}};b.b("__tr_ambtns",b.va.ab);b.l={};b.l.h=function(a){this.h=a};b.l.h.prototype.text=function(){var a=b.a.u(this.h),a="script"===a?"text":"textarea"===a?"value":"innerHTML";if(0==arguments.length)return this.h[a];var d=arguments[0];"innerHTML"===a?b.a.aa(this.h,d):this.h[a]=d};b.l.h.prototype.data=function(a){if(1===arguments.length)return b.a.f.get(this.h,"templateSourceData_"+a);b.a.f.set(this.h,"templateSourceData_"+
a,arguments[1])};b.l.O=function(a){this.h=a};b.l.O.prototype=new b.l.h;b.l.O.prototype.text=function(){if(0==arguments.length){var a=b.a.f.get(this.h,"__ko_anon_template__")||{};a.wa===G&&a.ga&&(a.wa=a.ga.innerHTML);return a.wa}b.a.f.set(this.h,"__ko_anon_template__",{wa:arguments[0]})};b.l.h.prototype.nodes=function(){if(0==arguments.length)return(b.a.f.get(this.h,"__ko_anon_template__")||{}).ga;b.a.f.set(this.h,"__ko_anon_template__",{ga:arguments[0]})};b.b("templateSources",b.l);b.b("templateSources.domElement",
b.l.h);b.b("templateSources.anonymousTemplate",b.l.O);var M;b.sa=function(a){a!=G&&!(a instanceof b.v)&&i(Error("templateEngine must inherit from ko.templateEngine"));M=a};b.ra=function(a,d,c,e,f){c=c||{};(c.templateEngine||M)==G&&i(Error("Set a template engine before calling renderTemplate"));f=f||"replaceChildren";if(e){var g=L(e);return b.k(function(){var h=d&&d instanceof b.A?d:new b.A(b.a.d(d)),j="function"==typeof a?a(h.$data,h):a,h=R(e,f,j,h,c);"replaceNode"==f&&(e=h,g=L(e))},o,{disposeWhen:function(){return!g||
!b.a.X(g)},disposeWhenNodeIsRemoved:g&&"replaceNode"==f?g.parentNode:g})}return b.t.oa(function(e){b.ra(a,d,c,e,"replaceNode")})};b.Fb=function(a,d,c,e,f){function g(a,b){S(b,j);c.afterRender&&c.afterRender(b,a)}function h(d,e){j=f.createChildContext(b.a.d(d),c.as);j.$index=e;var g="function"==typeof a?a(d,j):a;return R(o,"ignoreTargetNode",g,j,c)}var j;return b.k(function(){var a=b.a.d(d)||[];"undefined"==typeof a.length&&(a=[a]);a=b.a.da(a,function(a){return c.includeDestroyed||a===G||a===o||!b.a.d(a._destroy)});
b.a.Qa(e,a,h,c,g)},o,{disposeWhenNodeIsRemoved:e})};b.c.template={init:function(a,d){var c=b.a.d(d());if("string"!=typeof c&&!c.name&&(1==a.nodeType||8==a.nodeType))c=1==a.nodeType?a.childNodes:b.e.childNodes(a),c=b.a.Ab(c),(new b.l.O(a)).nodes(c);return{controlsDescendantBindings:m}},update:function(a,d,c,e,f){d=b.a.d(d());e=m;"string"==typeof d?c=d:(c=d.name,"if"in d&&(e=e&&b.a.d(d["if"])),"ifnot"in d&&(e=e&&!b.a.d(d.ifnot)));var g=o;"object"===typeof d&&"foreach"in d?g=b.Fb(c||a,e&&d.foreach||
[],d,a,f):e?(f="object"==typeof d&&"data"in d?f.createChildContext(b.a.d(d.data),d.as):f,g=b.ra(c||a,f,d,a)):b.e.ja(a);f=g;(d=b.a.f.get(a,"__ko__templateSubscriptionDomDataKey__"))&&"function"==typeof d.B&&d.B();b.a.f.set(a,"__ko__templateSubscriptionDomDataKey__",f)}};b.g.F.template=function(a){a=b.g.Z(a);return 1==a.length&&a[0].unknown||b.g.xb(a,"name")?o:"This template engine does not support anonymous templates nested within its templates"};b.e.z.template=m;b.b("setTemplateEngine",b.sa);b.b("renderTemplate",
b.ra);b.a.Ca=function(a,b,c){a=a||[];b=b||[];return a.length<=b.length?P(a,b,"added","deleted",c):P(b,a,"deleted","added",c)};b.b("utils.compareArrays",b.a.Ca);b.a.Qa=function(a,d,c,e,f){function g(a,b){t=k[b];v!==b&&(B[a]=t);t.la(v++);K(t.N);s.push(t);z.push(t)}function h(a,d){if(a)for(var c=0,e=d.length;c<e;c++)d[c]&&b.a.n(d[c].N,function(b){a(b,c,d[c].V)})}for(var d=d||[],e=e||{},j=b.a.f.get(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult")===G,k=b.a.f.get(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult")||
[],l=b.a.W(k,function(a){return a.V}),n=b.a.Ca(l,d),s=[],q=0,v=0,x=[],z=[],y=[],B=[],d=[],t,l=0,A,C;A=n[l];l++)switch(C=A.moved,A.status){case "deleted":C===G&&(t=k[q],t.k.B(),x.push.apply(x,K(t.N)),e.beforeRemove&&(y[l]=t,z.push(t)));q++;break;case "retained":g(l,q++);break;case "added":C!==G?g(l,C):(t={V:A.value,la:b.m(v++)},s.push(t),z.push(t),j||(d[l]=t))}h(e.beforeMove,B);b.a.n(x,e.beforeRemove?b.G:b.removeNode);h(e.beforeRemove,y);for(var l=0,j=b.e.firstChild(a),D;t=z[l];l++){t.N||b.a.extend(t,
ea(a,c,t.V,f,t.la));for(q=0;n=t.N[q];j=n.nextSibling,D=n,q++)n!==j&&b.e.Ha(a,n,D);!t.tb&&f&&(f(t.V,t.N,t.la),t.tb=m)}h(e.afterMove,B);h(e.afterAdd,d);b.a.f.set(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult",s)};b.b("utils.setDomNodeChildrenFromArrayMapping",b.a.Qa);b.q=function(){this.allowTemplateRewriting=p};b.q.prototype=new b.v;b.q.prototype.renderTemplateSource=function(a){var d=!(9>b.a.Y)&&a.nodes?a.nodes():o;if(d)return b.a.M(d.cloneNode(m).childNodes);a=a.text();return b.a.qa(a)};
b.q.L=new b.q;b.sa(b.q.L);b.b("nativeTemplateEngine",b.q);b.na=function(){var a=this.wb=function(){if("undefined"==typeof E||!E.tmpl)return 0;try{if(0<=E.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,c,e){e=e||{};2>a&&i(Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later."));var f=b.data("precompiled");f||(f=b.text()||"",f=E.template(o,"{{ko_with $item.koBindingContext}}"+f+"{{/ko_with}}"),
b.data("precompiled",f));b=[c.$data];c=E.extend({koBindingContext:c},e.templateOptions);c=E.tmpl(f,b,c);c.appendTo(w.createElement("div"));E.fragments={};return c};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){w.write("<script type='text/html' id='"+a+"'>"+b+"<\/script>")};0<a&&(E.tmpl.tag.ko_code={open:"__.push($1 || '');"},E.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};b.na.prototype=new b.v;v=new b.na;
0<v.wb&&b.sa(v);b.b("jqueryTmplTemplateEngine",b.na)}"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?J(module.exports||exports):"function"===typeof define&&define.amd?define(["exports"],J):J(u.ko={});m;
})();
